name: Publish to NuGet (Trusted Publishing)

on:
  release:
    types: [published]

permissions:
  contents: read
  actions: write

env:
  REALM_DISABLE_ANALYTICS: true
  DOTNET_NOLOGO: true

jobs:
  build-wrappers:
    name: Wrappers
    uses: ./.github/workflows/wrappers.yml

  build-packages:
    name: Build NuGet Packages
    if: always() && !cancelled() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled')
    needs:
      - build-wrappers
    runs-on: windows-latest
    timeout-minutes: 30
    outputs:
      package_version: ${{ steps.get-version.outputs.package_version }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: false
      - name: Register problem matchers
        run: |
          echo "::add-matcher::.github/problem-matchers/csc.json"
          echo "::add-matcher::.github/problem-matchers/msvc.json"
      - uses: actions/setup-dotnet@5d1464d5da459f3d7085106d52e499f4dc5d0f59
        with:
          dotnet-version: 8.0.x
      - name: Fetch wrappers for macos
        uses: actions/download-artifact@v4
        with:
          name: wrappers-macos
          path: wrappers/build
      - name: Fetch wrappers for catalyst
        uses: actions/download-artifact@v4
        with:
          name: wrappers-catalyst
          path: wrappers/build
      - name: Fetch wrappers for linux-x86_64
        uses: actions/download-artifact@v4
        with:
          name: wrappers-linux-x86_64
          path: wrappers/build
      - name: Fetch wrappers for linux-armhf
        uses: actions/download-artifact@v4
        with:
          name: wrappers-linux-armhf
          path: wrappers/build
      - name: Fetch wrappers for linux-aarch64
        uses: actions/download-artifact@v4
        with:
          name: wrappers-linux-aarch64
          path: wrappers/build
      - name: Fetch wrappers for android-armeabi-v7a
        uses: actions/download-artifact@v4
        with:
          name: wrappers-android-armeabi-v7a
          path: wrappers/build
      - name: Fetch wrappers for android-arm64-v8a
        uses: actions/download-artifact@v4
        with:
          name: wrappers-android-arm64-v8a
          path: wrappers/build
      - name: Fetch wrappers for android-x86
        uses: actions/download-artifact@v4
        with:
          name: wrappers-android-x86
          path: wrappers/build
      - name: Fetch wrappers for android-x86_64
        uses: actions/download-artifact@v4
        with:
          name: wrappers-android-x86_64
          path: wrappers/build
      - name: Fetch wrappers for windows-Win32
        uses: actions/download-artifact@v4
        with:
          name: wrappers-windows-Win32
          path: wrappers/build
      - name: Fetch wrappers for windows-x64
        uses: actions/download-artifact@v4
        with:
          name: wrappers-windows-x64
          path: wrappers/build
      - name: Fetch wrappers for windows-ARM64
        uses: actions/download-artifact@v4
        with:
          name: wrappers-windows-ARM64
          path: wrappers/build
      - name: Fetch wrappers for windows-uwp-Win32
        uses: actions/download-artifact@v4
        with:
          name: wrappers-windows-uwp-Win32
          path: wrappers/build
      - name: Fetch wrappers for windows-uwp-x64
        uses: actions/download-artifact@v4
        with:
          name: wrappers-windows-uwp-x64
          path: wrappers/build
      - name: Fetch wrappers for windows-uwp-ARM64
        uses: actions/download-artifact@v4
        with:
          name: wrappers-windows-uwp-ARM64
          path: wrappers/build
      - name: Fetch wrappers for iOS-Device
        uses: actions/download-artifact@v4
        with:
          name: wrappers-iOS-Device
          path: wrappers/build
      - name: Fetch wrappers for iOS-Simulator
        uses: actions/download-artifact@v4
        with:
          name: wrappers-iOS-Simulator
          path: wrappers/build
      - name: Fetch wrappers for tvOS-Device
        uses: actions/download-artifact@v4
        with:
          name: wrappers-tvOS-Device
          path: wrappers/build
      - name: Fetch wrappers for tvOS-Simulator
        uses: actions/download-artifact@v4
        with:
          name: wrappers-tvOS-Simulator
          path: wrappers/build
      - name: Add msbuild to PATH
        if: ${{ runner.os == 'Windows' }}
        uses: microsoft/setup-msbuild@70b70342ae97ca98d5eaad06cafd26d30f9592a9
      - name: Build Realm/Realm
        run: msbuild Realm/Realm -t:Pack -restore -p:Configuration=Release -p:PackageOutputPath=${{ github.workspace }}/Realm/packages
      - name: Build Realm/Realm.UnityUtils
        run: msbuild Realm/Realm.UnityUtils -t:Pack -restore -p:Configuration=Release -p:PackageOutputPath=${{ github.workspace }}/Realm/packages
      - name: Build Realm/Realm.UnityWeaver
        run: msbuild Realm/Realm.UnityWeaver -t:Pack -restore -p:Configuration=Release -p:PackageOutputPath=${{ github.workspace }}/Realm/packages
      - name: Read version
        id: get-version
        shell: bash
        run: |
          cd Realm/packages
          pkgVersion=$(find . -type f -name "Realm.Refurbished.*.nupkg" -exec basename {} \; | sed -n 's/Realm\.Refurbished\.\(.*\)\.nupkg$/\1/p')
          echo "package_version=$pkgVersion" >> $GITHUB_OUTPUT
      - name: Store artifacts for Realm.Refurbished.${{ steps.get-version.outputs.package_version }}
        uses: actions/upload-artifact@v4
        with:
          name: Realm.Refurbished.${{ steps.get-version.outputs.package_version }}
          path: Realm/packages/Realm.Refurbished.${{ steps.get-version.outputs.package_version }}.*nupkg
          retention-days: 30
          if-no-files-found: error

  publish-nuget:
    name: Publish to NuGet
    needs:
      - build-packages
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      actions: read
    steps:
      - uses: actions/setup-dotnet@5d1464d5da459f3d7085106d52e499f4dc5d0f59
        with:
          dotnet-version: 8.0.x
      - name: Download NuGet package
        uses: actions/download-artifact@v4
        with:
          name: Realm.Refurbished.${{ needs.build-packages.outputs.package_version }}
          path: ./packages
      - name: NuGet login (Trusted Publishing)
        id: nuget-login
        uses: nuget/login@v1
        with:
          user: Oleksii_Burianov
      - name: Publish to NuGet.org
        run: dotnet nuget push "./packages/*.nupkg" --api-key ${{ steps.nuget-login.outputs.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
